name: Patch
on:
#  push:
  schedule:
    - cron: "0 21 * * *"
  workflow_dispatch:
jobs:
  patch1:
    name: Patch Revanced-1
    permissions: write-all
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Set up jdk
        uses: actions/setup-java@v3.11.0
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Patch apk
        run: bash src/build/Revanced-1.sh
        env:
          repository: ${{ github.repository }}

      - name: Generate release info
        run: |
          echo "
          **Change log** :point_down:
          [Revanced](https://github.com/revanced/revanced-patches/releases/latest)
          [Revanced Extended](https://github.com/inotia00/revanced-patches/releases/latest)
          [Revanced Extended for Android 6 & 7](https://github.com/kitadai31/revanced-patches-android6-7/releases/latest)
          "> ${{ github.workspace }}-CHANGELOG.txt

      - name: Release
        uses: softprops/action-gh-release@v0.1.15
        with:
          files: |
            ./build/*
            revanced-version.txt
          name: Revanced & Revanced Extended
          tag_name: all
          body_path: ${{ github.workspace }}-CHANGELOG.txt
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
